server:
  port: 9000



spring:
  cloud:
    config:
      label: master
      uri: http://localhost:8888/
      profile: dev
    stream:
      kafka:
        binder:
          zk-nodes: localhost:2181
          brokers: localhost:9092
    bus:
      enabled: true
  application:
    name: config

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh



#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8001/eureka/







